import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Technical Share | Squad 10</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline text-orange-500">
        Hello Next.js
      </h1>
      <p className="text-2xl underline">with TailwindCSS</p>
    </div>
  );
}
